### ISSUE TITLE
1.5.0-9 & 1.5.0-11 Starstrike crashs Server [bug]

### ISSUE THREAD

**Issue by garnichtpascal** [Growlith1223/ArsMagica2#101]
When Starstrike hits an entity without life (for example the thrown rock from the air guardian or the laser from the guardins in vallina mc) the server crashs. I had a gravestone but no gravestone spawned so I lost all my items + spells.
Time: 12/13/16 9:05 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.util.EntityDamageSource.func_151519_b(SourceFile:47)
at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:105)
	at net.minecraft.network.play.server.SPacketCombatEvent.<init>(SourceFile:48)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:441)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1022)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:543)
	at am2.utils.SpellUtils.attackTargetSpecial(SpellUtils.java:189)
	at am2.entity.EntityThrownRock.HitObject(EntityThrownRock.java:296)
	at am2.entity.EntityThrownRock.func_70071_h_(EntityThrownRock.java:260)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.EntityDamageSource.func_151519_b(SourceFile:47)
	at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:105)
	at net.minecraft.network.play.server.SPacketCombatEvent.<init>(SourceFile:48)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:441)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1022)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:543)
	at am2.utils.SpellUtils.attackTargetSpecial(SpellUtils.java:189)
	at am2.entity.EntityThrownRock.HitObject(EntityThrownRock.java:296)
	at am2.entity.EntityThrownRock.func_70071_h_(EntityThrownRock.java:260)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

**Comment by garnichtpascal** [comment]
After a restart i was dead and i had the gravestones mod but there wasn't a gravestone so I had lost all my items.

**Comment by StarkRG** [comment]
While I can confirm that the Air Guardian has issues it's not causing our server to crash, merely hang and not respond. This occurs immediately after the spinny-break-block move (I can hear the blocks break but don't actually see them).

This is SMP on dedicated server. (nothing revealing in the logs)

**Comment by garnichtpascal** [comment]
I found out, that it was the spell starstrike. When starstrike hits an entity, which isn't a real mob or anything (like air guardins rocks which he throw) the server crashs.

**Comment by Growlith1223** [comment]
i legit can't reproduce this, if you could figure out if it actually is starstrike and not something else, that would be wonderful

**Comment by garnichtpascal** [comment]
It's starstrike. I don't tried it with an other spell which is like starstrike. When im fighting with an air guardian or a guardian from vanilla mc the server crashs and I lost all my Items.

**Comment by EdwinMindcraft** [comment]
Uh... The issue is starstrike hitting a player...
func_70097_a is attackEntityFrom.
func_70645_a is onDeath.
