### ISSUE TITLE
[1.5.0-15] -Using AM2 and Extra Utilities 2 breaks XU2's JEI plugin

### ISSUE THREAD

**Issue by The-Key** [Growlith1223/ArsMagica2#136]
This happens while using[ extrautils2-1.10.2-1.1.3c](https://github.com/rwtema/extrautilities),[ jei_1.10.2-3.14.2.401](https://github.com/mezz/JustEnoughItems), and ArsMagica2-1.10.2-1.5.0-15. If I remove AM2 then XU2's recipes show up again. Here is what happens when jei tries to register plugins:
```
[14:48:19] [Client thread/INFO]: Starting JEI...
[14:48:20] [Client thread/INFO]: Registering plugin: mezz.jei.plugins.vanilla.VanillaPlugin ...
[14:48:20] [Client thread/INFO]: Registered  plugin: mezz.jei.plugins.vanilla.VanillaPlugin in 169 ms
[14:48:20] [Client thread/INFO]: Registering plugin: com.rwtema.extrautils2.crafting.jei.XUJEIPlugin ...
[14:48:20] [Client thread/ERROR]: Failed to register mod plugin: class com.rwtema.extrautils2.crafting.jei.XUJEIPlugin
java.lang.NullPointerException
	at com.rwtema.extrautils2.machine.FoodEnergyRecipe.isValid(FoodEnergyRecipe.java:98) ~[FoodEnergyRecipe.class:?]
	at com.rwtema.extrautils2.machine.FoodEnergyRecipe.lambda$getInputValues$0(FoodEnergyRecipe.java:104) ~[FoodEnergyRecipe.class:?]
	at com.rwtema.extrautils2.machine.EnergyBaseRecipe.getCreativeStacks(EnergyBaseRecipe.java:76) ~[EnergyBaseRecipe.class:?]
	at com.rwtema.extrautils2.machine.FoodEnergyRecipe.getInputValues(FoodEnergyRecipe.java:104) ~[FoodEnergyRecipe.class:?]
	at com.rwtema.extrautils2.recipes.SingleInputStackMatchRecipeBase.getJEIInputItemExamples(SingleInputStackMatchRecipeBase.java:33) ~[SingleInputStackMatchRecipeBase.class:?]
	at com.rwtema.extrautils2.crafting.jei.XUJEIPlugin.register(XUJEIPlugin.java:109) ~[XUJEIPlugin.class:?]
	at mezz.jei.JeiStarter.registerPlugins(JeiStarter.java:142) [JeiStarter.class:?]
	at mezz.jei.JeiStarter.start(JeiStarter.java:48) [JeiStarter.class:?]
	at mezz.jei.ProxyCommonClient.loadComplete(ProxyCommonClient.java:111) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:53) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:803) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[14:48:20] [Client thread/INFO]: Registering plugin: am2.compat.JEIHandler ...
[14:48:20] [Client thread/INFO]: Registered  plugin: am2.compat.JEIHandler in 15 ms
[14:48:20] [Client thread/INFO]: Registering plugin: mezz.jei.plugins.jei.JEIInternalPlugin ...
[14:48:20] [Client thread/INFO]: Registered  plugin: mezz.jei.plugins.jei.JEIInternalPlugin in 5 ms
[14:48:20] [Client thread/INFO]: Building recipe registry...
[14:48:20] [Client thread/INFO]: Built    recipe registry in 232 ms
[14:48:20] [Client thread/INFO]: Building item filter...
[14:48:24] [Client thread/INFO]: Built	item filter in 3728 ms
[14:48:24] [Client thread/INFO]: Building runtime...
[14:48:24] [Client thread/INFO]: Built    runtime in 45 ms
[14:48:24] [Client thread/INFO]: Sending runtime to plugin: mezz.jei.plugins.vanilla.VanillaPlugin ...
[14:48:24] [Client thread/INFO]: Sending runtime to plugin: am2.compat.JEIHandler ...
[14:48:24] [Client thread/INFO]: Sending runtime to plugin: mezz.jei.plugins.jei.JEIInternalPlugin ...
[14:48:24] [Client thread/INFO]: Finished Starting JEI in 4675 ms

**Comment by Growlith1223** [comment]
i'll check it out but from the looks of it, Extra Utils doesn't seem to be checking for nulls in its registry but like i said, i'll check it out

**Comment by Traverse-Joe** [comment]
are you using mine tweaker or mod tweaker it's been verified that it's latest Version removes the recipes from EXU2

**Comment by The-Key** [comment]
This bug still occurs with only jei xu2 and am2 installed. Also my full pack includes craft tweaker 3.0.16 but the xu2 recipes still show up in jei without am2.
