### ISSUE TITLE
[1.5.0-15] Crash - breaking essence refiner

### ISSUE THREAD

**Issue by oryfoxer** [Growlith1223/ArsMagica2#144]
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=active, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at am2.blocks.tileentity.TileEntityEssenceRefiner.setActiveTexture(TileEntityEssenceRefiner.java:195)
	at am2.blocks.tileentity.TileEntityEssenceRefiner.func_73660_a(TileEntityEssenceRefiner.java:189)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:211)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:1312)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjl000(WorldServer.java:1299)
	at net.minecraft.world.World.func_72939_s(World.java:1282)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:714)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by TheIcyOne** [comment]
Which Sponge version are you using?

**Comment by oryfoxer** [comment]
1.10.2 - 5.1.0-BETA-2022 - Matching Forge Version

**Comment by Growlith1223** [comment]
hopefully has been fixed. if this persists, reply here again/open(if possible) and i'll check it out
