### ISSUE TITLE
[1.5.0-16a] AM2 crash

### ISSUE THREAD

**Issue by oryfoxer** [Growlith1223/ArsMagica2#167]
Time: 1/26/17 1:21 PM
Description: Exception ticking world

java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at am2.world.WitchwoodTreeHuge.generateLeafNodeList(WitchwoodTreeHuge.java:135)
	at am2.world.WitchwoodTreeHuge.func_180709_b(WitchwoodTreeHuge.java:433)
	at am2.world.AM2WorldDecorator.generateTree(AM2WorldDecorator.java:168)
	at am2.world.AM2WorldDecorator.generateOverworld(AM2WorldDecorator.java:130)
	at am2.world.AM2WorldDecorator.generate(AM2WorldDecorator.java:93)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.lang.System.arraycopy(Native Method)
	at am2.world.WitchwoodTreeHuge.generateLeafNodeList(WitchwoodTreeHuge.java:135)
	at am2.world.WitchwoodTreeHuge.func_180709_b(WitchwoodTreeHuge.java:433)
	at am2.world.AM2WorldDecorator.generateTree(AM2WorldDecorator.java:168)
	at am2.world.AM2WorldDecorator.generateOverworld(AM2WorldDecorator.java:130)
	at am2.world.AM2WorldDecorator.generate(AM2WorldDecorator.java:93)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: world
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by TheIcyOne** [comment]
This occurred while generating a world, yes?

Did you have any other mods installed?

**Comment by oryfoxer** [comment]
quite a few yes. Was getting concurrent prior, then applied the updated ars build which is now producing these. 

from https://github.com/Growlith1223/ArsMagica2/issues/162

**Comment by TheIcyOne** [comment]
The modlist is otherwise identical?

**Comment by oryfoxer** [comment]
http://www.technicpack.net/modpack/a-1102-pack.938599/mods

Is the mod list.

**Comment by Growlith1223** [comment]
fixed, it was due to me experimenting with some memory optimizations and forgot to remove it in that version. will be fixed in next version!
