### ISSUE TITLE
Chronal Anchor crashing/disconnecting players

### ISSUE THREAD

**Issue by xenxero1** [Growlith1223/ArsMagica2#293]
Testing some Chronal Anchor spell on my SMP server, using the Spinycraft V2 pack; I cast it on myself for 30 seconds. At the end of the effect, I was disconnected. Upon reconnection the Chronal Anchor ability triggered properly.  I cast this on another player; the same thing except their client crashed (potentially unrelated. Bad hardware, full memory cache). I then cast it on a zombie. After 30 seconds the server crashed. The zombie was then despawned but that was likely due to the server crash, and not a direct chronal anchor issue.

I am unable to retrieve the crash log at the moment, but i will try to post it here tonight.

Am2 version: -17b
Minecraft: 1.10.2
Pack: Spinycraft V2 1.2.1
Forge: (will Pull later)

**Comment by Gorgok** [comment]
ArsMagica2-1.10.2-1.5.0-18
Forge 1.10.2-12.18.3.2281

Same issue, end of anchor kicks player off server, though not a full client crash. This is the best i can do about the "crash", taken from the server latest.log file.

`[01:14:26] [Server thread/WARN]: Failed to handle packet for /192.168.1.13:50305
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_70082_c(FF)V
	at am2.buffs.BuffEffectTemporalAnchor.stopEffect(BuffEffectTemporalAnchor.java:41) ~[BuffEffectTemporalAnchor.class:?]
	at am2.buffs.BuffEffect.effectEnding(BuffEffect.java:33) ~[BuffEffect.class:?]
	at am2.buffs.BuffEffect.func_76455_a(BuffEffect.java:60) ~[BuffEffect.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:589) ~[sf.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:343) ~[sf.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359) ~[rw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932) ~[sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
	... 9 more`
