### ISSUE TITLE
The name ubcores:igneous_stone_tile.ore has been registered twice

### ISSUE THREAD

**Issue by TomberWolf** [Growlith1223/ArsMagica2#294]
There seems to be conflicts with UBC Ore Registrar (https://minecraft.curseforge.com/projects/ubc-ore-registrar).

As soon as I want to use Ars Magica 2, both, the Server and the Client crashes on startup.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.239-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.204-universal.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.3.2.1.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 3/21/17 9:02 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from UBC Ore Registrar (ubcores)
Caused by: java.lang.IllegalArgumentException: The name ubcores:igneous_stone_tile.ore has been registered twice, for Block{ubcores:igneous_stone_tile.ore} and Block{null}.
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:458)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:829)
	at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:254)
	at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:153)
	at exterminatorjeff.undergroundbiomes.intermod.OreEntry.doRegister(OreEntry.java:48)
	at exterminatorjeff.undergroundbiomes.api.names.Entry.register(Entry.java:60)
	at exterminatorjeff.undergroundbiomes.intermod.OresRegistry.createOre(OresRegistry.java:138)
	at exterminatorjeff.undergroundbiomes.intermod.OresRegistry.setupOre(OresRegistry.java:160)
	at com.mr208.UBCOres.UBCHelper.registerOreBlock(UBCHelper.java:11)
	at com.mr208.UBCOres.UBCHelper.registerModOresWithMeta(UBCHelper.java:33)
	at com.mr208.UBCOres.Mods.ArsMagica2(Mods.java:50)
	at com.mr208.UBCOres.CommonProxy.onPreInit(CommonProxy.java:18)
	at com.mr208.UBCOres.ClientProxy.onPreInit(ClientProxy.java:11)
	at com.mr208.UBCOres.UBCOres.preInit(UBCOres.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 297120512 bytes (283 MB) / 801947648 bytes (764 MB) up to 12831227904 bytes (12236 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -Xmn512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 Optifine OptiFine_1.10.2_HD_U_D7 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCH	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCH	NotEnoughItems{2.1.3.204} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.204-universal.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.6.239-universal.jar) 
	UCH	koresample{1.10.2-L1} [Kore Sample] (anchienttreesl-koresample-1.10.2-L1.1.jar) 
	UCH	dendrology{1.10.2-L1.0.2} [Ancient Trees] (anchienttreesl-dendrology-1.10.2-L1.0.2.jar) 
	UCH	animania{1.0.4} [Animania] (animania-1.10-1.0.4.jar) 
	UCH	antiqueatlas{1.9.4-4.3.0} [Antique Atlas] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCH	AntiqueAtlasOverlay{1.2} [AntiqueAtlasOverlay] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCH	arsmagica2{1.5.017} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCH	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCH	AutoSapling{1.3.3} [AutoSapling] (Autosapling-1.3.3-MC1.10.jar) 
	UCH	BiomesOPlenty{5.0.0.2162} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar) 
	UCH	CodeChickenLib{2.5.6.239} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.6.239-universal.jar) 
	UCH	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCH	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(17mar17).jar) 
	UCH	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCH	dsurround{3.3.2.1} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.3.2.1.jar) 
	UCH	farseek{2.1} [Farseek] (Farseek-1.9.4-2.1.jar) 
	UCH	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCH	FloodLights{1.2.7-145} [Flood Lights] (FloodLights-1.9.4-1.2.7-145.jar) 
	UCH	CodeChickenCore{2.4.0.101} [CodeChicken Core] (NEI-CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCH	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCH	streams{0.3} [Streams] (Streams-1.9.4-0.3.jar) 
	UCH	ToughAsNails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.jar) 
	UCH	undergroundbiomes{0.9.beta.16} [Underground Biomes] (UndergroundBiomesConstructs-1.10-0.9-beta.16.jar) 
	UCE	ubcores{@VERSION@} [UBC Ore Registrar] (UBCOres-2.0.0.jar) 
	Loaded coremods (and transformers): 
FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  farseek.core.FarseekClassTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  am2.asm.Transformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.239-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.204-universal.jar)
  codechicken.nei.asm.NEITransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.3.2.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.78' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: `

**Comment by Growlith1223** [comment]
this is not the right place to be posting this crash. being as this has nothing to do with ars magica(especially since there's no igneous stone tile in the mod either).

**Comment by TomberWolf** [comment]
Hmm. Thats strange. Why does it just happen as soon as AM2 is in the mod folder?

**Comment by Growlith1223** [comment]
who knows, but i would try contacting them first, they are the ones attempting to do compat with the mod lol

if they come back and say that yes, it's on my side, then i'll look into it.
