### ISSUE TITLE
ArsMagica2-1.10.2-1.5.0-18 (Forge 2185) -  Unable to load block sub-model:

### ISSUE THREAD

**Issue by rinart73** [Growlith1223/ArsMagica2#366]
`[13:07:35] [Client thread/ERROR] [FML/]: Unable to load block sub-model: 'arsmagica2:block/celestial_prism_cullface.json
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Loader am2.models.CullfaceModelLoader@7b9e178d returned missing model while loading model arsmagica2:block/celestial_prism_cullface.json
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:157) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModelOrLogError(ModelLoaderRegistry.java:203) [ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.BlockStateLoader$ForgeVariant.process(BlockStateLoader.java:206) [BlockStateLoader$ForgeVariant.class:?]
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:756) [ModelLoader$WeightedRandomModel.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1185) [ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) [ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:325) [ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:185) [byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) [ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by melekaiah** [comment]
I have the very same error, cant manage to rack down the compatability  though
