### ISSUE TITLE
[Version 1.5.0-9] Earth Guardian drops nothing

### ISSUE THREAD

**Issue by drewbit** [Growlith1223/ArsMagica2#66]
Afaik, the Eath Guardian is supposed to drop Blue Infinity Orbs. When you kill the boss this doesn't happen.

**Comment by Growlith1223** [comment]
so many issues have popped up since i went away for a little while xD

**Comment by Zieg777** [comment]
Does he not drop them? I just killed one the other day and got one I thought. Though admittedly, I was mostly concerned with how fast I could kill him than the actual drops.

**Comment by Growlith1223** [comment]
i just killed one right now, and he dropped his usual stuff, Earth Essence and a blue infinity orb. are you absolutely sure it didn't go into your inventory or something?

**Comment by Builderb0y** [comment]
I've had several different bosses fail to drop things, though it seems to be mostly random. If it helps though, the arcane guardian will sometimes print a stack trace to the server console when it fails to drop things:

```
[08:13:12] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_31]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_31]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at am2.bosses.EntityArcaneGuardian.func_70628_a(EntityArcaneGuardian.java:216) ~[EntityArcaneGuardian.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184610_a(EntityLivingBase.java:1100) ~[sf.class:?]
	at net.minecraft.entity.EntityLiving.func_184610_a(EntityLiving.java:555) ~[sg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1080) ~[sf.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970) ~[sf.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73) ~[yx.class:?]
	at am2.bosses.AM2Boss.func_70097_a(AM2Boss.java:189) ~[AM2Boss.class:?]
	at am2.bosses.EntityArcaneGuardian.func_70097_a(EntityArcaneGuardian.java:108) ~[EntityArcaneGuardian.class:?]
	at am2.bosses.AM2Boss.func_70965_a(AM2Boss.java:199) ~[AM2Boss.class:?]
	at net.minecraft.entity.boss.EntityDragonPart.func_70097_a(SourceFile:40) ~[wz.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1293) ~[zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1226) ~[lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1040) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) ~[iu.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) ~[iu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_31]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```

The earth guardian on the other hand has dropped its orb 3 out of 5 times (so far), but hasn't printed any stack traces yet. It did [crash my client](http://pastebin.com/TUbaxrC6) twice though, but it seems to be entirely forge code so I'm not sure what can be done about that. It should also be noted that I'm currently using 1.5.0-6, not 1.5.0-9; mainly because of the dupe bug with digging spells.

**Comment by Growlith1223** [comment]
i wonder if it's because of the chance for the special item to be dropped... i'll look into it, thanks for letting me know about the error!

**Comment by Growlith1223** [comment]
yep, it's because of the special item being dropped lol

**Comment by Builderb0y** [comment]
Edit 1: The fire guardian has now crashed my client too with the same UnknownFormatConversionException as the earth guardian. No errors in the server console.

**Comment by Growlith1223** [comment]
can you confirm that it also crashes on the arcane guardian?

**Comment by Builderb0y** [comment]
I've used the arcane guardian for most of my green skill points, (I'm guessing I've killed it at least 20 times now), and it hasn't crashed me yet.

**Comment by Growlith1223** [comment]
ok and that format crash happens when you kill the boss or?

**Comment by Builderb0y** [comment]
So far, seems to be triggered by taking damage from them, though not every time.

**Comment by Growlith1223** [comment]
is it by death or just in general taking damage?

**Comment by Builderb0y** [comment]
General damage. I have project E's gem armor, so no guardian has managed to kill me yet.

**Comment by Growlith1223** [comment]
is it from the projectile or when he hits you directly?

**Comment by Zieg777** [comment]
Wait, how are you able to fight the arcane guardian at all? I get a crash as soon as he tries to heal himself. Same with the fire guardian.

**Comment by Growlith1223** [comment]
i've fixed it in the github code, i just haven't done a new release yet(i will in a few hours)

**Comment by Zieg777** [comment]
Ah. Still catching up on changes in the issues page. Thanks. Those crashes made it hard to get any red orbs. I ended up cheating in an arcane book because I know I can fight him but he kept crashing me (I tossed 4 arcane essences into lava for payment)

**Comment by Builderb0y** [comment]
Not sure how the fire guardian attacked. All I know is that my screen was tilted for a few seconds until it finished generating the crash report.

As for the arcane guardian, I've never seen it do anything at all besides knocking me back when I attack it. It just sits there and dies slowly against some diamond spikes. (I make the final hit though, since diamond spikes don't seem to be able to kill it completely)
